### ISSUE TITLE
Checkpoint file

### ISSUE THREAD

**Issue by BurntCalcium** [LimGuenTaek/Pedestrian_Detection#5]
Hi @LimGuenTaek,
Thank you for making this implementation public. But I am unable to reproduce this implementation because there is no checkpoint file of trained weights. Would it be possible for you to kindly make the checkpoint file available for download?
Thank you

**Comment by LimGuenTaek** [comment]
I updated READMe and source code 

When you download the dataset, you can execute the code immediately.

Also, I uploaded checkpoint(epoch 1) to check code works

If you have difficulty executing the code, please leave an issue.
